pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven("https://artifactory-external.vkpartner.ru/artifactory/superappkit-maven-public/")
        maven("https://jitpack.io")
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
rootProject.name = "Visify"

include(":client")
project(":client").apply {
    projectDir = file("apps/b2c")
    name = "client"
}
include(":business")
project(":business").apply {
    projectDir = file("apps/b2b")
    name = "business"
}

include(":core:api:models")
include(":core:storage")
include(":core:ktx")
include(":core:util")
include(":core:repository")
include(":core:bus")
include(":core:pref")
include(":core:location")
include(":core:api:http")
include(":core:api:sse")
include(":core:time")
include(":core:image")
include(":core:notifications")
include(":core:navigator:impl")
include(":core:navigator:api")
include(":ui:kit")
include(":core:arch")
include(":feature:camera")
include(":ui:icons")
include(":feature:auth:api")
include(":feature:auth:impl")
include(":feature:debug:api")
include(":feature:debug:impl")
include(":feature:debug:noop")
include(":feature:settings:api")
include(":feature:settings:impl")
include(":feature:user:api")
include(":feature:user:impl")
include(":feature:profile:api")
include(":feature:profile:client")
include(":feature:profile:business")
include(":feature:selectcity:api")
include(":feature:selectcity:impl")
include(":feature:order:market:impl")
include(":feature:order:market:api")
include(":feature:catalog:api")
include(":feature:categories:api")
include(":feature:common:models")
include(":feature:categories:impl")
include(":feature:order:common")
include(":ui:models")
include(":feature:common:mappers")
include(":feature:organisation:api")
include(":feature:favor:impl")
include(":feature:favor:api")
include(":feature:favor:impl")
include(":feature:favor:api")
include(":feature:favourite:api")
include(":feature:organisation:impl")
include(":feature:order:visit:api")
include(":feature:master:api")
include(":feature:feedback:api")
include(":feature:feedback:impl")
include(":feature:order:create:api")
include(":feature:order:create:impl")
include(":feature:order:edit:impl")
include(":feature:order:edit:api")
include(":feature:order:detailed:api")
include(":feature:order:detailed:impl")
include(":feature:master:impl")
include(":feature:favourite:impl")
include(":feature:masters:api")
include(":feature:masters:impl")
include(":feature:organisations:impl")
include(":feature:organisations:api")
include(":feature:filters:api")
include(":feature:filters:impl")
include(":feature:map:impl")
include(":feature:map:api")
include(":feature:catalog:impl")
include(":feature:order:my:api")
include(":feature:dashboard:api")
include(":feature:dashboard:impl")
include(":core:configuration")
include(":core:database")
include(":feature:timesheet:api")
include(":feature:timesheet:impl")

include(":feature:order:visit:impl")
include(":feature:order:my:impl")
include(":feature:calendar:api")
include(":feature:calendar:impl")

include(":feature:order:detailedmarket:api")
include(":feature:order:detailedmarket:impl")
include(":feature:order:manage:api")
include(":feature:order:manage:impl")
include(":feature:order:suggestion:api")
include(":feature:im:api")
include(":feature:order:suggestion:impl")
include(":feature:im:impl")
include(":feature:order:api")
include(":feature:order:domain")
include(":feature:employee:api")
include(":feature:employee:impl")
include(":feature:order:addphoto:api")
include(":feature:order:addphoto:impl")
include(":feature:salons")
include(":feature:salons:api")
include(":feature:salons:impl")
